M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu22.04.1} date 2026-02-16T18:37:52+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-16T18:37:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X158.785Y-100.91
X158.785Y-106.69
M30
